name: Format Code with clang-format and gofmt

on:
  push:
    branches: [ go ]
  pull_request:
    branches: [ go ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install dependencies for clang-format and Go
    - name: Install clang-format and Go
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format
        sudo apt-get install -y golang-go

    # Format C++ files with clang-format
    - name: Run clang-format
      run: find . -type f \( -name "*.cpp" -o -name "*.hpp" \) | xargs clang-format -i

    # Format Go files with gofmt
    - name: Run gofmt
      run: find . -type f -name "*.go" | xargs gofmt -w

    # Check for modified files
    - name: Check for modified files
      id: git-check
      run: |
        git diff --exit-code || echo "modified=true" >> $GITHUB_OUTPUT
      shell: bash

    # Commit formatted files if changes exist
    - name: Commit formatted files
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-format C++ and Go code"
        git push